### ISSUE TITLE
If "@" is added to this regexp, it resolves the issue which is also seen in replace-requires

### ISSUE THREAD

**Issue by iambumblehead** [bendrucker/has-require#2]
https://github.com/bendrucker/has-require/blob/master/index.js#L19

If "@" is added to this regexp, it resolves the issue which is also seen in replace-requires

https://github.com/bendrucker/replace-requires/issues/3

```
var anyRegExp = createRegExp('[A-Za-z0-9@/_.-]+')
```

**Comment by bendrucker** [comment]
Good catch, should be fixed
